project:
  type: website

website:
  title: "Cross Country Meet Summaries"
  navbar:
    background: primary
    right:
      - href: about.qmd
        text: About 
      - href: https://datawolf04.github.io
        text: DataWorld
    logo: eatSleepRun.png
  draft-mode: visible

format:
  html:
    theme:
      - sketchy
      - brand
      - custom-theme.scss
    css: styles.css

execute:
  freeze: auto


